### ISSUE TITLE
Could not find artifact when running lein collect-dev

### ISSUE THREAD

**Issue by zendevil** [ClockworksIO/rum-natal#3]
When I run lein collect-dev in the projectname/projectname directory, I get the following error:

```
Could not find artifact org.clojure:core.async:jar:0.4.582 in central (https://repo1.maven.org/maven2/)
Could not find artifact org.clojure:core.async:jar:0.4.582 in clojars (https://repo.clojars.org/)
This could be due to a typo in :dependencies, file system permissions, or network issues.
If you are behind a proxy, try setting the 'http_proxy' environment variable.
```
What's the fix?

**Comment by 7tupel** [comment]
Hi @zendevil could you give me a short hint what the problem was? Disclaimer: rum-natal is currently going through a heavy re-design with breaking changes because I'm splitting the leiningen template from the actual react native abstractions. The master might not always be stable for now.
